name: Build iOS Flet App

on:
  pull_request:
  push:
    branches:
      - main  # 根据您的默认分支名称调整

jobs:
  build-ios-app:
    runs-on: macos-latest  # 使用最新的 macOS 运行器

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rosetta 2
      run: sudo softwareupdate --install-rosetta --agree-to-license

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods -v 1.16.0

    - name: Build iOS app with Flet
      run: |
        flet build ipa
        
    - name: Upload iOS app artifact (on push only)
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: iOS-Flet-App
        path: build/ios/ipa/*.ipa
        retention-days: 1