name: Build iOS Flet App

on:
  pull_request:
  push:
    branches:
      - main  # 根据您的默认分支名称调整


env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

  # Python version to use
  PYTHON_VERSION: 3.12.8

  # Ensures Python uses UTF-8 encoding by default
  PYTHONUTF8: 1

  # Disables rich text formatting in Flet CLI output
  FLET_CLI_NO_RICH_OUTPUT: 1

  # Disables progress bars when using UV
  UV_NO_PROGRESS: 1

jobs:
  build-ios-app:
    runs-on: macos-latest  # 使用最新的 macOS 运行器

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet-cli

    - name: Build iOS app with Flet
      run: |
        cp -r AgentUtils App/AgentUtils
        cp -r Business App/Business
        cp pyproject.toml ./App
        flet build ipa --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION 
        
    - name: Upload iOS app artifact (on push only)
      uses: actions/upload-artifact@v4
      with:
        name: iOS-Flet-App
        path: build/ios/ipa/*.ipa
        retention-days: 1